---
name: "OSV Scanner"

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  check:
    name: Check with OSV Scanner
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Install OSV Scanner
      run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
    - name: OSV Scanner
      run: go run ./cmd/osv-scanner -r .
